/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mywardrobeprogram.ui;

import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import mywardrobeprogram.dao.persistence.BrandPersist;
import mywardrobeprogram.model.Brand;

/**
 * UI frame to capture brand related information to persist 
 * 
 * @author Natalia Luiz
 */
public class BrandFrame extends javax.swing.JDialog {

    /**
     * Creates new form BrandFrame
     */
    public BrandFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
	 JPanel image = new ImagePanel(new ImageIcon(getClass().getResource("tumblr_nchsszxGMM1rf6a91o1_500.jpg")).getImage());
        add(image);

        repaint();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brandName = new javax.swing.JLabel();
        recommendedLabel = new javax.swing.JLabel();
        shoppingMallLabel = new javax.swing.JLabel();
        brandNameTxt = new javax.swing.JTextField();
        recommendedTxt = new javax.swing.JTextField();
        shoppingMallTxt = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        brandName.setText("Brand name");

        recommendedLabel.setText("Recommended");

        shoppingMallLabel.setText("Shopping Mall");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(brandName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(brandNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recommendedLabel)
                                    .addComponent(shoppingMallLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recommendedTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(shoppingMallTxt))))
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandName)
                    .addComponent(brandNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recommendedLabel)
                    .addComponent(recommendedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoppingMallLabel)
                    .addComponent(shoppingMallTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
    /**
     * Performs validation for data entered into UI and persists to db
     * 
     * @throws SQLException Database unavailable to persist brand
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String brandName = brandNameTxt.getText();
        String recommended = recommendedTxt.getText();
        String shoppingMall = shoppingMallTxt.getText();

        if (brandName == null || brandName.length() == 0) {
            JOptionPane.showMessageDialog(this, "Brand name is required ");
        } else if (recommended == null || recommended.length() == 0) {
            JOptionPane.showMessageDialog(this, "Recommended field is required ");
        } else if (shoppingMall == null || shoppingMall.length() == 0) {
            JOptionPane.showMessageDialog(this, "Shopping Mall is required ");
        } else {
            Brand brand = new Brand();
            brand.setName(brandName);
            brand.setRecommended(recommended);
            brand.setShoppingMall(shoppingMall);
            brand.setId(brandID);
            try {
                persistence.execute(brand);
            } catch (SQLException sqlE) {
                sqlE.printStackTrace();
                JOptionPane.showMessageDialog(this, "Unable to persist brand ");
            }
            setVisible(false);

        }

    }//GEN-LAST:event_addButtonActionPerformed

    
    /**
     * Displays an existing brand
     * 
     * @param displayBrand shows newly created brands details
     */
    public void displayData(Brand displayBrand) {
        brandID = displayBrand.getId();
        brandNameTxt.setText(displayBrand.getName());
        recommendedTxt.setText(displayBrand.getRecommended());
        shoppingMallTxt.setText(displayBrand.getShoppingMall());
        addButton.setText("update");

    }
    /**
     * Resets UI screen 
     */
    public void reset() {
        brandID = null;
        brandNameTxt.setText("");
        recommendedTxt.setText("");
        shoppingMallTxt.setText("");
        addButton.setText("add");
    }

    public void setPersistence(BrandPersist persistence) {
        this.persistence = persistence;
    }

    private Integer brandID;
    private BrandPersist persistence;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel brandName;
    private javax.swing.JTextField brandNameTxt;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel recommendedLabel;
    private javax.swing.JTextField recommendedTxt;
    private javax.swing.JLabel shoppingMallLabel;
    private javax.swing.JTextField shoppingMallTxt;
    // End of variables declaration//GEN-END:variables
}
