/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mywardrobeprogram.ui;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 * UI application help display
 * 
 * @author Natalia Luiz
 */
public class HelpDialog extends javax.swing.JDialog {
    private static final String MESSAGE = "Welcome to the My Wardrobe Program! This Help facility will assist you, the user, with navigation throughout this program. \n\nUsers - New and Existing Users: If you are not already an existing user, you are restricted from the wardrobe tab, which is a drop down of viewing your wardrobe and viewing brands. \n\nIf you would like to able to access these functions, you are required to register as a new user and then log in with your created username and password. \n\nThis will allow you access to the wardrobe tab, which is a drop down of viewing your wardrobe where you can add, edit (e.g. change the colour of your dress from yellow to pink) and delete clothing items in your closet. \n\nFurthermore, you are allowed access to view brands where you can add brands, edit brands (e.g. change your newly created brand name from Sissy Boy to The Lot) and delete brands that exist in your wardrobe. \n\nThank you for accessing the help function, enjoy!";
    
    
    /**
     * Creates new form HelpDialog
     * 
     * Code to add a images as the background
     */
    public HelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
	JPanel image = new ImagePanel(new ImageIcon(getClass().getResource("IMG_6441_1024.jpg")).getImage());
        add(image);

        repaint();
        pack();
       
        helpText.setEditable(false);
	helpText.setText(MESSAGE);
	helpText.setWrapStyleWord(true);
	helpText.setLineWrap(true);
	helpText.setCaretPosition(0);
        
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        helpText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        helpText.setColumns(20);
        helpText.setRows(5);
        jScrollPane2.setViewportView(helpText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea helpText;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
