/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mywardrobeprogram.ui;

import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import mywardrobeprogram.dao.WardrobeDao;
import mywardrobeprogram.dao.persistence.impl.ClothingAddPersist;
import mywardrobeprogram.dao.persistence.impl.ClothingUpdatePersist;
import mywardrobeprogram.model.Clothing;
import mywardrobeprogram.ui.listener.FormWindowListener;
import mywardrobeprogram.ui.model.ClothingTableModel;

/**
 * UI to show all clothing items in the users wardrobe
 * 
 * @author Natalia Luiz
 */
public class ViewMyWardrobe extends javax.swing.JFrame {

    /**
     * Creates new form ViewMyWardrobe
     * 
     * Code to add an image as a background of the ViewMyWardrobeFrame
     */
    public ViewMyWardrobe() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new FormWindowListener());
	 JPanel image = new ImagePanel(new ImageIcon(getClass().getResource("IMG_5605_1024.jpg")).getImage());
        add(image);

        repaint();
        pack();
    }
    /**
     * Retrieving all items of clothing for user 
     */
    public void refreshData (){
        try {
            List<Clothing> usersWardrobe = WardrobeDao.getInstance().findClothingByUserId(LoginForm.loggedInUser.getId());
        
            jTable1.setModel(new ClothingTableModel(usersWardrobe));
        } catch(SQLException sqle) {
            System.out.println("Unable to retrieve users wardrobe.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Take a look what you have in your closet!");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Type", "Size", "Colour", "Style"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addGap(0, 166, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Displays UI to add new item of clothing
     * 
     * @param evt click event
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        displayClothingFrame.setPersist(new ClothingAddPersist(), "add");
	displayClothingFrame.setLocationRelativeTo(this);
	displayClothingFrame.reset();
        displayClothingFrame.setVisible(true);
        
        refreshData();
    }//GEN-LAST:event_addButtonActionPerformed
     /**
     * Delete selected item of clothing from table
     * 
     * @param evt click event 
     */
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedClothing = jTable1.getSelectedRow();
        if (selectedClothing != -1){
            ClothingTableModel model = (ClothingTableModel)jTable1.getModel();
            Clothing selected = model.getSelected(selectedClothing);
	}else {
		    JOptionPane.showMessageDialog(this, "Select a row to edit");
		    }
            try {
                WardrobeDao.getInstance().deleteClothingByID(selected.getId());
                refreshData();
            }catch (SQLException sql){
                JOptionPane.showMessageDialog(this, "Unable to delete item");
            }
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed
     /**
     * shows UI to edit a selected item of clothing the user selected from the table
     */
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int selectedRow = jTable1.getSelectedRow();
	if(selectedRow !=-1){
	    ClothingTableModel model = (ClothingTableModel)jTable1.getModel();
	    Clothing selectedItem = model.getSelected(selectedRow);
        
	     displayClothingFrame.setPersist(new ClothingUpdatePersist(), "update");
	     displayClothingFrame.reset();
	     displayClothingFrame.display(selectedItem);
	     displayClothingFrame.setLocationRelativeTo(this);
	     displayClothingFrame.setVisible(true);
	     
	      refreshData();
	}else {
	    JOptionPane.showMessageDialog(this, "Select a row to edit");
	}
        
        
       
    }//GEN-LAST:event_editButtonActionPerformed

    ClothingFrame displayClothingFrame = new ClothingFrame(this);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
