/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mywardrobeprogram.ui;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import mywardrobeprogram.dao.WardrobeDao;

/**
 * Wardrobe application entry point.Creates all UIs the system uses
 *
 * @author Natalia Luiz
 */
public class WardrobeScreen extends javax.swing.JFrame implements WindowListener {

    private RegisterForm registerUI;
    private LoginForm loginUI;
    private ViewMyWardrobe viewUI;
    private ViewBrandsFrame brandsUI;

    /**
     * Constructor Create UI dialogs
     */
    public WardrobeScreen() {
	initComponents();
	try {
	    WardrobeDao.getInstance();
	    registerUI = new RegisterForm();
	    registerUI.setVisible(false);
	    loginUI = new LoginForm(this);
	    loginUI.setVisible(false);
	    registerItem.setEnabled(true);
	    viewUI = new ViewMyWardrobe();
	    viewUI.setVisible(false);
	    ViewMyProfileMenuItem.setEnabled(false);
	    brandsUI = new ViewBrandsFrame();
	    brandsUI.setVisible(false);
	    wardrobeMenu.setEnabled(false);

	    this.addWindowListener(this);

	    JPanel image = new ImagePanel(new ImageIcon(getClass().getResource("fitted-sliding-wardrobe-pink-white-glass-bedroom-thumb.png")).getImage());
	    add(image);

	    repaint();
	    pack();
	} catch (SQLException sqlE) {
	    sqlE.printStackTrace();
	    JOptionPane.showMessageDialog(this, "Unable to create database connection. Is the server running?");
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        accountMenu = new javax.swing.JMenu();
        registerItem = new javax.swing.JMenuItem();
        LoginMenueItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        wardrobeMenu = new javax.swing.JMenu();
        viewBrandsMenuItem = new javax.swing.JMenuItem();
        ViewMyProfileMenuItem = new javax.swing.JMenuItem();
        userHelp = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        accountMenu.setText("Account");
        accountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountMenuActionPerformed(evt);
            }
        });

        registerItem.setText("Register");
        registerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerItemActionPerformed(evt);
            }
        });
        accountMenu.add(registerItem);

        LoginMenueItem.setText("Login");
        LoginMenueItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginMenueItemActionPerformed(evt);
            }
        });
        accountMenu.add(LoginMenueItem);

        exitMenuItem.setText("Exit ");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        accountMenu.add(exitMenuItem);

        jMenuBar1.add(accountMenu);

        wardrobeMenu.setText("Wardrobe");

        viewBrandsMenuItem.setText("View Brands");
        viewBrandsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBrandsMenuItemActionPerformed(evt);
            }
        });
        wardrobeMenu.add(viewBrandsMenuItem);

        ViewMyProfileMenuItem.setText("View My Wardrobe");
        ViewMyProfileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMyProfileMenuItemActionPerformed(evt);
            }
        });
        wardrobeMenu.add(ViewMyProfileMenuItem);

        jMenuBar1.add(wardrobeMenu);

        userHelp.setText("Help");
        userHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userHelpActionPerformed(evt);
            }
        });

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        userHelp.add(aboutMenuItem);

        jMenuBar1.add(userHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Display register new user frame
     *
     * @param evt click event
     */
    private void registerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerItemActionPerformed
	registerUI.requestFocus();
	registerUI.setLocationRelativeTo(this);
	registerUI.setVisible(true);
    }//GEN-LAST:event_registerItemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
	// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed
    /**
     * Display login UI
     *
     * @param evt click event
     */
    private void LoginMenueItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginMenueItemActionPerformed
	loginUI.requestFocus();
	loginUI.setLocationRelativeTo(this);
	loginUI.setVisible(true);
    }//GEN-LAST:event_LoginMenueItemActionPerformed
    /**
     * Display UI to list all clothing items for user
     *
     * @param evt click event
     */
    private void ViewMyProfileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMyProfileMenuItemActionPerformed
	viewUI.refreshData();
	viewUI.requestFocus();
	viewUI.setLocationRelativeTo(this);
	viewUI.setVisible(true);
    }//GEN-LAST:event_ViewMyProfileMenuItemActionPerformed

    private void accountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountMenuActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_accountMenuActionPerformed
    /**
     * Exit application
     *
     * @param evt click event
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
	System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    /**
     * Display UI to list all brands
     *
     * @param evt click event
     */
    private void viewBrandsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBrandsMenuItemActionPerformed
	brandsUI.refreshData();
	brandsUI.setLocationRelativeTo(this);
	brandsUI.setVisible(true);
    }//GEN-LAST:event_viewBrandsMenuItemActionPerformed

    private void userHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userHelpActionPerformed

    }//GEN-LAST:event_userHelpActionPerformed
    /**
     * Display help UI
     *
     * @param evt click event
     */
    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
	HelpDialog help = new HelpDialog(this, true);
	help.setLocationRelativeTo(help);
	help.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed
    /**
     * Enable menu items after logging in
     */
    public void enableMenuItems() {
	registerItem.setEnabled(true);
	ViewMyProfileMenuItem.setEnabled(true);
	wardrobeMenu.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(WardrobeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(WardrobeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(WardrobeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(WardrobeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new WardrobeScreen().setVisible(true);
	    }
	});
    }

    @Override
    public void windowOpened(WindowEvent we) {
    }

    @Override
    public void windowClosing(WindowEvent we) {
    }

    @Override
    public void windowClosed(WindowEvent we) {
    }

    @Override
    public void windowIconified(WindowEvent we) {
    }

    @Override
    public void windowDeiconified(WindowEvent we) {
    }

    @Override
    public void windowActivated(WindowEvent we) {
    }

    @Override
    public void windowDeactivated(WindowEvent we) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LoginMenueItem;
    private javax.swing.JMenuItem ViewMyProfileMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu accountMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem registerItem;
    private javax.swing.JMenu userHelp;
    private javax.swing.JMenuItem viewBrandsMenuItem;
    private javax.swing.JMenu wardrobeMenu;
    // End of variables declaration//GEN-END:variables
}
